version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/koron-go/tdata
    steps:
      - run:
          name: Golang version
          command: go version
      - checkout
      - run:
          name: Install dependencies
          command: go get -v -t -d ./...
      - run:
          name: Test all
          command: go test -v ./...
